# Generated by Django 4.2.3 on 2025-04-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_winnerpick_actual_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnerpick',
            name='away_score',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='winnerpick',
            name='home_score',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='winnerpick',
            name='year',
            field=models.PositiveSmallIntegerField(default=2025),
        ),
    ]
