# Generated by Django 4.2.3 on 2025-06-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_alter_winnerpick_away_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winnerpick',
            options={'ordering': ['player', 'week_number']},
        ),
        migrations.AlterField(
            model_name='winnerpick',
            name='player',
            field=models.CharField(choices=[('Mom', 'Mom'), ('Mr. C.', 'Mr. C.'), ('Tiara', 'Tiara'), ('Stefaun', 'Stefaun')], default='Mr C', max_length=200, null=True),
        ),
    ]
