# Generated by Django 5.2.4 on 2025-08-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0010_alter_winnerpick_actual_winner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="winnerpick",
            name="player",
            field=models.CharField(
                choices=[
                    ("Mom", "Mom"),
                    ("Mr C", "Mr C"),
                    ("Tiara", "Tiara"),
                    ("Stefaun", "Stefaun"),
                ],
                default="Mr C",
                max_length=200,
                null=True,
            ),
        ),
    ]
